### ISSUE TITLE
command not found: start

### ISSUE THREAD

**Issue by rhyslbw** [cmather/meteor-start#1]
I'm getting 'command not found: start'.

lrwxr-xr-x  1 Rhys  staff    34 11 Nov 02:43 start -> /Users/Rhys/src/meteor-start/start

I've also tried this with the script in the project folder rather than a link, but no joy

**Comment by cmather** [comment]
You might have to do > ./start with a dot and forward slash to indicate the executable is in your current directory.

**Comment by rhyslbw** [comment]
That did the trick, thanks Chris.
